[package]
name = "swift_swallow_tree_search"
version = "0.1.0"
edition = "2024"

[dependencies]
swift_swallow.workspace = true
swift_swallow_rpc.workspace = true

rand = "0.9.0"
rand_xoshiro = "0.7.0"

rustc-hash = "2.1.1"

libc = "0.2"
anyhow = "1.0.99"

serde.workspace = true
serde_json.workspace = true
