[package]
name = "swift_swallow_tree_search"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
swift_swallow.workspace = true
swift_swallow_rpc.workspace = true

rand = "0.9.0"
rand_xoshiro = "0.7.0"

rustc-hash = "2.1.1"

either = "1.15.0"

anyhow = "1.0.99"
clap = { version = "4.5.47", features = ["derive"] }

serde.workspace = true
serde_json.workspace = true

libc = "0.2"
