[package]
name = "swift_swallow_tree_search"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
swift_swallow.workspace = true
swift_swallow_rpc.workspace = true

rand.workspace = true
rand_xoshiro.workspace = true

rustc-hash = "2.1.1"
indexmap = "2.14.0"

either = "1.15.0"

anyhow = "1.0.99"
clap = { version = "4.5.47", features = ["derive"] }

serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
criterion = { version = "0.8.2", features = ["html_reports"] }

[[bench]]
name = "bench"
harness = false
